### ISSUE TITLE
AttributeError: type object 'QgsMapLayerProxyModel' has no attribute 'Filters'

### ISSUE THREAD

**Issue by danschef** [jakimowb/virtual-raster-builder#1]
Not sure if this issue tracker is the right one as the QGIS plugin manager still points to BitBucket, however, the VRT builder currently crashes with this exception (plugin cannot be loaded):

```python
Couldn't load plugin 'vrtbuilderplugin' due to an error when calling its initGui() method 

AttributeError: type object 'QgsMapLayerProxyModel' has no attribute 'Filters' 
Traceback (most recent call last):
  File "/home/gfz-fe/mambaforge/envs/enpt_full_dev/share/qgis/python/qgis/utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "/home/gfz-fe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder/vrtbuilderplugin.py", line 48, in initGui
    from vrtbuilder.widgets import VRTBuilderWidget
  File "/home/gfz-fe/mambaforge/envs/enpt_full_dev/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gfz-fe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder/widgets.py", line 28, in 
    from .externals.qps.maptools import SpatialExtentMapTool
  File "/home/gfz-fe/mambaforge/envs/enpt_full_dev/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gfz-fe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder/externals/qps/maptools.py", line 54, in 
    from .utils import *
  File "/home/gfz-fe/mambaforge/envs/enpt_full_dev/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gfz-fe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder/externals/qps/utils.py", line 2420, in 
    class SelectMapLayersDialog(QgsDialog):
  File "/home/gfz-fe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder/externals/qps/utils.py", line 2421, in SelectMapLayersDialog
    class LayerDescription(object):
  File "/home/gfz-fe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder/externals/qps/utils.py", line 2423, in LayerDescription
    def __init__(self, info: str, filters: QgsMapLayerProxyModel.Filters, allowEmptyLayer=False):
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'QgsMapLayerProxyModel' has no attribute 'Filters'


Python version: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 11:02:03) [GCC 12.3.0] 
QGIS version: 3.34.1-Prizren Prizren, exported 
```

I guess it is the same issue like in https://github.com/EnMAP-Box/enmap-box/issues/713.

**Comment by user2856** [comment]
Plugin seems abandoned. Workaround that updates the external `qps` library documented on [GIS StackExchange](https://gis.stackexchange.com/q/500126/2856).

**Comment by danschef** [comment]
> Workaround that updates the external qps library documented on [GIS StackExchange](https://gis.stackexchange.com/q/500126/2856).

@jakimowb, this looks like there is an easy fix for this - probably worth to integrate it into a version update?
